### ISSUE TITLE
Week 8 Exercise

### ISSUE THREAD

**Issue by esajdak** [esajdak/Week8#1]
@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Looks like you've got the process for consuming a rest service down. 

The call https://github.com/esajdak/Week8/blob/9f06ca1e44d8b97e913f337b052d4082eeaf8426/src/main/java/io/swagger/persistence/PetDao.java#L18 would be more flexible if the method accepted an id and concatenated it here rather than having 87  hard-coded into the request.
